export const FAKE_POPULARS = [
  {
    backdrop_path: "/8qlKzvR68dH0ZaJFG9XBEctvvUo.jpg",
    first_air_date: "2011-02-12",
    genre_ids: [35],
    id: 63935,
    name: "Les Mystères de l'amour",
    origin_country: ["FR"],
    original_language: "fr",
    original_name: "Les Mystères de l'amour",
    overview: "Across more than 100",
    popularity: 2821.316,
    poster_path: "/mtUhIHbhw0GCacVnPam8p4vwejB.jpg",
    vote_average: 6.4,
    vote_count: 7,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/8tFY7CfP1KBGEEy9W0RflLvpFme.jpg",
    id: 2140,
    name: "Everybody Loves Raymond",
    original_language: "en",
    original_name: "Everybody Loves Raymond",
    overview:
      "Ray Barone is a successful sportswriter living on Long Island with his wife Debra, daughter Ally, and twin sons, Geoffrey and Michael. That's the good news. The bad news? Ray's meddling parents, Frank and Marie, live directly across the street and embrace the motto \"Su casa es mi casa,\" infiltrating their son's home to an extent unparalleled in television history.",
    poster_path: "/dcCnVVggEBfNpzHrqzDJqhE6tGP.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 60.827,
    first_air_date: "1996-09-13",
    vote_average: 6.793,
    vote_count: 472,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/9GWU1AyNqUYIUl1tU7CvXEHUVs9.jpg",
    id: 2996,
    name: "The Office",
    original_language: "en",
    original_name: "The Office",
    overview:
      "Documentary-style sitcom set in the offices of a Slough paper merchant.",
    poster_path: "/23Y3M7bYYhOCIHfbMWGX57hK2zl.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 19.391,
    first_air_date: "2001-07-09",
    vote_average: 7.854,
    vote_count: 660,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/qfR4wMsqkBUu4LLtiQvtqAgL7zQ.jpg",
    id: 31756,
    name: "Impact",
    original_language: "en",
    original_name: "Impact",
    overview:
      "Impact is a mini-series about a meteor shower which eventually sends the moon on a collision course with Earth. The two-part mini-series premiered February 14 and 15, 2009 on the Canadian premium television channel Super Channel and was also shown on ABC on June 21 and 28, 2009 and on Alpha TV on September 2011 .",
    poster_path: "/tW93Zpgin2YllmhnwjXnh5EeGAy.jpg",
    media_type: "tv",
    genre_ids: [10759, 10765],
    popularity: 10.117,
    first_air_date: "2009-02-14",
    vote_average: 6.022,
    vote_count: 67,
    origin_country: ["DE"],
  },
  {
    adult: false,
    backdrop_path: "/rNVKSn9g7PA4u3IzZTX1DbulGkk.jpg",
    id: 326,
    name: "Red Dwarf",
    original_language: "en",
    original_name: "Red Dwarf",
    overview:
      "The adventures of the last human alive and his friends, stranded three million years into deep space on the mining ship Red Dwarf.",
    poster_path: "/dAaVWMhCCrSuimSETs9Z5ZTZQ3v.jpg",
    media_type: "tv",
    genre_ids: [35, 10765],
    popularity: 28.396,
    first_air_date: "1988-02-15",
    vote_average: 8.043,
    vote_count: 314,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/jqweieg5sg0HLlVjugP9fWDiIJq.jpg",
    id: 1996,
    name: "The Flintstones",
    original_language: "en",
    original_name: "The Flintstones",
    overview:
      "The misadventures of two modern-day Stone Age families, the Flintstones and the Rubbles.",
    poster_path: "/30P6ifagQ3fguTsI33KMmDLTAx6.jpg",
    media_type: "tv",
    genre_ids: [10751, 16, 35, 10762],
    popularity: 74.622,
    first_air_date: "1960-09-30",
    vote_average: 7.364,
    vote_count: 762,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/f1sjJoT21vH9snaCjipKlMM1DCF.jpg",
    id: 60905,
    name: "Salem",
    original_language: "en",
    original_name: "Salem",
    overview:
      "Set in the volatile world of 17th century Massachusetts, 'Salem' explores what really fueled the town's infamous witch trials and dares to uncover the dark, supernatural truth hiding behind the veil of this infamous period in American history. In Salem, witches are real, but they are not who or what they seem.",
    poster_path: "/sS9pnQSjH2COeBvhRalfyZlN4TJ.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 18],
    popularity: 21.655,
    first_air_date: "2014-04-20",
    vote_average: 7.365,
    vote_count: 270,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/lBeLaL6WcIAxRqA972F2HH9zxcM.jpg",
    id: 43529,
    name: "Labyrinth",
    original_language: "en",
    original_name: "Labyrinth",
    overview:
      "Jumping back and forth between modern and medieval France, the lives of two women separated by centuries, are united in their search for an ancient artifact.",
    poster_path: "/7ze6V3XYVBeQe3Y9opRw3Hbyhbh.jpg",
    media_type: "tv",
    genre_ids: [10765],
    popularity: 11.313,
    first_air_date: "2012-11-24",
    vote_average: 5.7,
    vote_count: 60,
    origin_country: ["ZA", "GB", "DE"],
  },
  {
    adult: false,
    backdrop_path: "/hxSEqdFRUKjn61vqNn958d08mk6.jpg",
    id: 68837,
    name: "Justice League Action",
    original_language: "en",
    original_name: "Justice League Action",
    overview:
      "Batman, Superman and Wonder Woman lead the DC Super Heroes against their most infamous foes.",
    poster_path: "/7BitEKENa2uiP48uOZHjY21Zi7L.jpg",
    media_type: "tv",
    genre_ids: [10759, 16, 10751, 10765],
    popularity: 31.198,
    first_air_date: "2016-12-16",
    vote_average: 7.197,
    vote_count: 66,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mgvMMxKz4eDLeompM9oJRDufNdW.jpg",
    id: 2286,
    name: "The Real Ghostbusters",
    original_language: "en",
    original_name: "The Real Ghostbusters",
    overview:
      "The continuing adventures of paranormal investigators Dr. Peter Venkman, Dr. Egon Spengler, Dr. Ray Stantz, Winston Zeddemore, their secretary Janine Melnitz and their mascot ghost Slimer.",
    poster_path: "/j1xlBYeyOQcH51xQc4gEFJK6o13.jpg",
    media_type: "tv",
    genre_ids: [10759, 16, 35, 9648],
    popularity: 19.468,
    first_air_date: "1986-09-13",
    vote_average: 7.495,
    vote_count: 205,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/tMRdEsMg9MyXAkcufK9YJEeIaNW.jpg",
    id: 1400,
    name: "Seinfeld",
    original_language: "en",
    original_name: "Seinfeld",
    overview:
      "A stand-up comedian and his three offbeat friends weather the pitfalls and payoffs of life in New York City in the '90s. It's a show about nothing.",
    poster_path: "/aCw8ONfyz3AhngVQa1E2Ss4KSUQ.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 145.722,
    first_air_date: "1989-07-05",
    vote_average: 8.3,
    vote_count: 1568,
    origin_country: ["US"],
  },
  ,
];
